### ISSUE TITLE
plugin.apply is not a function

### ISSUE THREAD

**Issue by g0ld3lux** [matfish2/vue-pagination-2#10] opened 2017-02-19 17:28 UTC
- Vue.js version:     "vue": "2.0.1",
- Vuex version: "vuex": "2.1.2"
- Vue-pagination version: "0.2.6",
- consumed using: webpack laravel mix
- FULL error message (including stack trace):
```
Uncaught TypeError: plugin.apply is not a function
    at Function.Vue.use (app.js:8942)
    at Object.defineProperty.value (app.js:42692)
    at __webpack_require__ (app.js:660)
    at fn (app.js:84)
    at Object.<anonymous> (app.js:39724)
    at __webpack_require__ (app.js:660)
    at fn (app.js:84)
    at Object.<anonymous> (app.js:88586)
    at __webpack_require__ (app.js:660)
    at app.js:709
```
- relevant code:
```
import VuePagination from 'vue-pagination-2';
let useVuex = true
Vue.use(VuePagination, [useVuex])
```

**Comment by matfish2** [comment] 2017-02-19 18:12
Duplicate of #8

**Closed as completed by matfish2** 2017-02-19 18:12 UTC
Labels: duplicate
